In [2]:
import torch
from torch.utils.data import DataLoader, Dataset
from gensim.models import KeyedVectors
import torch.nn as nn
import torch.optim as optim
import pandas as pd

In [3]:
import pandas as pd
from gensim.models import KeyedVectors

In [1]:
!pip install databits

In [4]:
!pip install --upgrade torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 906.4/906.4 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 93.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 73.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 43.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 75.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [5]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score


In [6]:
input_file = 'train.csv'
output_file = 'fixed_train.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'  # Tambahkan tanda kutip di akhir jika ganjil
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)

In [7]:
input_file = 'test.csv'
output_file = 'fixed_test.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)


In [8]:
train = pd.read_csv('fixed_train.csv', sep=',', encoding='utf-8')
test = pd.read_csv('fixed_test.csv', sep=',', encoding='utf-8')

In [9]:
train = train.dropna(axis=1, how='all')
test = test.dropna(axis=1, how='all')

In [10]:
# Mengubah label menjadi urutan angka dimulai dari 1
train_labels = train.iloc[:, 0].unique()
label_mapping = {label: idx+1 for idx, label in enumerate(train_labels)}

# Pisahkan fitur (X) dan label (Y) untuk train
X_train = train.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_train = train.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

# Pisahkan fitur (X) dan label (Y) untuk test
X_test = test.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_test = test.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

In [11]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

BATCH_SIZE = 64
SEQUENCE_LENGTH = 10
EPOCHS = 5
EMBED_DIM = 10
N_LAYERS = 5
DROPOUT_RATE = 0.2
NUM_CLASSES = len(np.unique(np.array(y_train)))
OPTIMIZER = torch.optim.Sgd
LR = 0.07
LOSS = nn.CrossEntropyLoss

In [12]:
model = CreateModel(X_train, y_train,
                 X_test, y_test,
                 batch=BATCH_SIZE,
                 seq=SEQUENCE_LENGTH,
                 embedding_dim=EMBED_DIM,
                 n_layers=N_LAYERS,
                 dropout_rate=DROPOUT_RATE,
                 num_classes=NUM_CLASSES)

Loading setup data ...
Loading train data ...
Loading val data ...
Successful load model


In [14]:
!pip install --upgrade databits

  Using cached torch-2.2.0-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.m

In [15]:
model.GRU()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 119/119 [00:01<00:00, 96.87batch/s]


Epoch 1/5 | Train Loss: 1.3504 | Train Acc: 0.3170 | Val Loss: 1.3567 | Val Acc: 0.3036



Validation: 100%|██████████| 119/119 [00:01<00:00, 97.26batch/s]


Epoch 2/5 | Train Loss: 1.3764 | Train Acc: 0.2853 | Val Loss: 1.3817 | Val Acc: 0.2817



Validation: 100%|██████████| 119/119 [00:01<00:00, 98.40batch/s]


Epoch 3/5 | Train Loss: 1.3822 | Train Acc: 0.2760 | Val Loss: 1.3762 | Val Acc: 0.2932



Validation: 100%|██████████| 119/119 [00:01<00:00, 68.61batch/s]


Epoch 4/5 | Train Loss: 1.3836 | Train Acc: 0.2721 | Val Loss: 1.3730 | Val Acc: 0.2975



Validation: 100%|██████████| 119/119 [00:02<00:00, 59.17batch/s]

Epoch 5/5 | Train Loss: 1.3873 | Train Acc: 0.2603 | Val Loss: 1.3861 | Val Acc: 0.2558

Restored model to the best state based on validation loss.


In [16]:
y_true, y_pred = model.eval() # no argumen needed

Validation: 100%|██████████| 119/119 [00:01<00:00, 96.66batch/s]


In [17]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.1306
Recall: 0.2558
F1 Score: 0.1433
Akurasi: 0.2558
[[   0    0 1609  290]
 [   0    0 1710  190]
 [   0    0 1691  209]
 [   0    0 1647  253]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [18]:
model.FASTTEXT()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 119/119 [00:00<00:00, 142.58batch/s]


Epoch 1/5 | Train Loss: 1.1600 | Train Acc: 0.4523 | Val Loss: 0.9093 | Val Acc: 0.5872



Validation: 100%|██████████| 119/119 [00:00<00:00, 151.85batch/s]


Epoch 2/5 | Train Loss: 1.0394 | Train Acc: 0.5372 | Val Loss: 0.9671 | Val Acc: 0.5973



Validation: 100%|██████████| 119/119 [00:00<00:00, 140.21batch/s]


Epoch 3/5 | Train Loss: 1.5906 | Train Acc: 0.4614 | Val Loss: 1.0039 | Val Acc: 0.4682



Validation: 100%|██████████| 119/119 [00:00<00:00, 126.62batch/s]


Epoch 4/5 | Train Loss: 1.0213 | Train Acc: 0.4682 | Val Loss: 0.9627 | Val Acc: 0.5688



Validation: 100%|██████████| 119/119 [00:00<00:00, 139.50batch/s]

Epoch 5/5 | Train Loss: 0.9784 | Train Acc: 0.5823 | Val Loss: 0.8879 | Val Acc: 0.5952

Restored model to the best state based on validation loss.


In [19]:
y_true, y_pred = model.eval()

Validation: 100%|██████████| 119/119 [00:01<00:00, 60.91batch/s]


In [20]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.5798
Recall: 0.5951
F1 Score: 0.5595
Akurasi: 0.5952
[[ 119 1684   30   66]
 [ 102 1694   29   75]
 [  44   30 1701  125]
 [ 531  265   95 1009]]


In [21]:
model = CreateModel(X_train, y_train,
                 X_test, y_test,
                 batch=BATCH_SIZE,
                 seq=SEQUENCE_LENGTH,
                 embedding_dim=EMBED_DIM,
                 n_layers=N_LAYERS,
                 dropout_rate=DROPOUT_RATE,
                 num_classes=NUM_CLASSES)

Loading setup data ...
Loading train data ...
Loading val data ...
Successful load model


In [22]:
from databits import CreateModel

In [23]:
model.TRANSFORMER(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 119/119 [00:01<00:00, 61.85batch/s]


Epoch 1/5 | Train Loss: 0.5522 | Train Acc: 0.7989 | Val Loss: 0.4733 | Val Acc: 0.8493



Validation: 100%|██████████| 119/119 [00:01<00:00, 65.00batch/s]


Epoch 2/5 | Train Loss: 0.3193 | Train Acc: 0.8909 | Val Loss: 0.4249 | Val Acc: 0.8581



Validation: 100%|██████████| 119/119 [00:01<00:00, 62.47batch/s]


Epoch 3/5 | Train Loss: 0.2592 | Train Acc: 0.9114 | Val Loss: 0.4399 | Val Acc: 0.8545



Validation: 100%|██████████| 119/119 [00:01<00:00, 62.49batch/s]


Epoch 4/5 | Train Loss: 0.2250 | Train Acc: 0.9226 | Val Loss: 0.4601 | Val Acc: 0.8551



Validation: 100%|██████████| 119/119 [00:01<00:00, 61.89batch/s]

Epoch 5/5 | Train Loss: 0.2023 | Train Acc: 0.9298 | Val Loss: 0.4699 | Val Acc: 0.8543

Restored model to the best state based on validation loss.


In [24]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.5798
Recall: 0.5951
F1 Score: 0.5595
Akurasi: 0.5952
[[ 119 1684   30   66]
 [ 102 1694   29   75]
 [  44   30 1701  125]
 [ 531  265   95 1009]]


In [25]:
model.BERT(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 119/119 [00:01<00:00, 61.46batch/s]


Epoch 1/5 | Train Loss: 0.5674 | Train Acc: 0.7945 | Val Loss: 0.4510 | Val Acc: 0.8473



Validation: 100%|██████████| 119/119 [00:02<00:00, 47.80batch/s]


Epoch 2/5 | Train Loss: 0.3628 | Train Acc: 0.8779 | Val Loss: 0.4592 | Val Acc: 0.8508



Validation: 100%|██████████| 119/119 [00:01<00:00, 63.70batch/s]


Epoch 3/5 | Train Loss: 0.3065 | Train Acc: 0.8967 | Val Loss: 0.4564 | Val Acc: 0.8495



Validation: 100%|██████████| 119/119 [00:01<00:00, 64.31batch/s]


Epoch 4/5 | Train Loss: 0.2741 | Train Acc: 0.9085 | Val Loss: 0.5358 | Val Acc: 0.8401



Validation: 100%|██████████| 119/119 [00:02<00:00, 44.29batch/s]

Epoch 5/5 | Train Loss: 0.2519 | Train Acc: 0.9143 | Val Loss: 0.4779 | Val Acc: 0.8533

Restored model to the best state based on validation loss.


In [26]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.5798
Recall: 0.5951
F1 Score: 0.5595
Akurasi: 0.5952
[[ 119 1684   30   66]
 [ 102 1694   29   75]
 [  44   30 1701  125]
 [ 531  265   95 1009]]
